baseURL = "certwatcher.io"
languageCode = "en-us"
title = "Certwatcher Documentation"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2
[[menu.main]]
    name = "Github"
    url = "https://github.com/drfabiocastro/certwatcher"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Getting Started'
  homepage_intro = 'Learn how to use certwatcher engine to write your own custom template to catch phishing sites and much more.'
  homepage_image = 'images/terminal.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_og_title = "Learn how to use certwatcher engine to write your own custom template."
    meta_og_type = "website"
    meta_og_url = "https://certwatcher.io/"
    meta_og_image = "https://certwatcher.io/images/logo.svg"
    meta_og_description = "Certwatcher.io is a SSL/TLS certificate monitoring and management tool that automates continuous certificate"
    meta_twitter_card = "summary"
    meta_twitter_site = "@drfabiocastro"
    meta_twitter_creator = "@drfabiocastro"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"